# Generated by Django 5.1.7 on 2025-03-07 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
